### ISSUE TITLE
[Imp] 对于含有空牌组的牌堆拒绝加载

### ISSUE THREAD

**Issue by Xiangze-Li** [sealdice/sealdice-core#683]
这种情况几乎不可能是编写者预期内的情况。即使编写者真的想要一个空字符串，ta也可以使用 `"key" = [""]` 的形式。

Followup #682

**Comment by fy0** [comment]
建议是不加载空的牌组，而不是整个牌堆都不加载？因为可能有的大牌堆写错了，有些用户只是去用，不清楚怎么改。

如果难以在加载的同时，报出错误提示，那么就选择整个不加载并报错。

**Comment by Xiangze-Li** [comment]
> 建议是不加载空的牌组，而不是整个牌堆都不加载？因为可能有的大牌堆写错了，有些用户只是去用，不清楚怎么改。
> 
> 如果难以在加载的同时，报出错误提示，那么就选择整个不加载并报错。

不合理的。

含有空牌堆是作者的开发错误，这种错误应该由作者在开发时自行修改完毕。而不应该由用户发现效果不符合预期后自行修改。

如果允许只跳过空牌堆，反而不利于作者发现自己的错误，可能在作者测试不充分的情况下被忽视。

**Comment by Xiangze-Li** [comment]
# 放弃实现: 实现难度与获得的收益不对等

## json 牌堆

```json
{
  "_keys": [],
  "A": [ "keys: {_keys}" ]
}
```

以上情况中, `_keys` 为空是合法使用, 即所有牌组都不可见. 同时 `_keys` 本身也是一个牌组. 

如果要拒绝空牌组, 需要对作为元数据的牌组做复杂的特判.

## toml 牌堆

```toml
["114514种论证"]
export = true
visible = true
options = []
cloud_extra = true
options_urls = [
  "http://example.com/xxx",
]
```

在以上情况中, 由于配置了云端获取选项, `options` 为空应当被视为合法, 静态分析不生效.

## yaml 牌堆

快点放弃支持吧!
